### PR TITLE
fix(root): fixes navigation bar scrolling

### PR DESCRIPTION
**Pull request by ad9242**
## Summary of the changes

Fixes issue where bottom elements in navigation bar could not be seen without scrolling main content

## Related issue

#139 

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

### CODE REVIEW

**Review by GCHQ-Developer-465 — COMMENTED** [review]
I have tested this with the build link and still get the same issue. It scrolls until Toast component and then I have to scroll the website to go down to the other components...

Screenshot 2024-05-28 at 12 18 41

**Comment by ad9242** [comment]
> I have tested this with the build link and still get the same issue. It scrolls until Toast component and then I have to scroll the website to go down to the other components...
> 
> Screenshot 2024-05-28 at 12 18 41

I didn't factor in the cookies banner into the calculation. Do you think it needs to? I feel like you would have either accepted or declined it

**Comment by GCHQ-Developer-465** [comment]
> > I have tested this with the build link and still get the same issue. It scrolls until Toast component and then I have to scroll the website to go down to the other components...
> > Screenshot 2024-05-28 at 12 18 41
> 
> @GCHQ-Developer-465 - I didn't factor in the cookies banner into the calculation. Do you think it needs to? I feel like you would have either accepted or declined it

I believe that you still would need to consider it I'm afraid.
Due to when you even accept the cookie banner the error still occurs. This bug still would occur until the user clicks 'hide cookie message'. (See below)
Screenshot 2024-05-28 at 12 52 00

Users who have not used the ICDS before will land on the page with the cookie banner and they tend to not interact with it. Therefore a consideration into having the cookie banner accounted for in this instance would be necessary.

If there is no 'official' fix for this we could use your solution as a temporary fix. Although we do not want to keep revisiting this fix / issue, so a final solution would be grand! 
Thanks ☺️

**Review by GCHQ-Developer-465 — APPROVED** [review]
Awesome work! 👍

This works now (see screenshot below!)
Thanks for including this in. 

Screenshot 2024-05-30 at 09 19 29
Screenshot 2024-05-30 at 09 19 43

**Review by GCHQ-Developer-530 — APPROVED** [review]

**Pull request merged**
