### PR TITLE
feat(root): add short title to top navigation

### PR DESCRIPTION
**Pull request by GCHQ-Developer-530**
## Summary of the changes

Add short title to top navigation and code example to top navigation component page.

Will need to test locally until [the ui-kit change](https://github.com/mi6/ic-ui-kit/pull/901) has been merged into main.

## Related issue

[853 in ui-kit](https://github.com/mi6/ic-ui-kit/issues/853)

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

### CODE REVIEW

**Review by GCHQ-Developer-741 — APPROVED** [review]

**Review by jd239 — CHANGES_REQUESTED** [review]
Shouldn't we add `short-app-title` to the main top navigation as well or waiting for the component to be published.

**Review by jd239 — APPROVED** [review]

**Comment by jd239** [comment]
Will this be merged in once the updates have been published?

**Review by gd2910 — DISMISSED** [review]

**Comment by gd2910** [comment]
Looks correct code-wise but the build isn't working as intended, the short-app-title is in the DOM but doesn't seem to drop down on small screen.

**Review by gd2910 — APPROVED** [review]

**Comment by jd239** [comment]
Will approve and merge once 2.2.0 has been published.

**Pull request merged**
