### PR TITLE
Fixed code examples for the page-header component. Small typo on the …

### PR DESCRIPTION
**Pull request by BenHammersley**
…subheading prop

## Summary of the changes

The code examples for the page header component had a typo, where the subheader prop had a hyphen in it

## Related issue

Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.

## Checklist

- [ ] I have manually accessibility tested any changes, if relevant.

### CODE REVIEW

**Comment by MI6-451** [comment]
Thank you very much for your contribution, would you mind modifying your commit to use [conventional commits](https://github.com/mi6/ic-design-system/blob/main/CONTRIBUTING.md#git-commit) as outlined in our contribution documentation and then we can get your change reviewed and merged.

**Review by ad9242 — CHANGES_REQUESTED** [review]
Good spot and thanks for contributing!

The React snippets also use "subHeading" which is not correct. It should also be lowercase "subheading".

Would you mind correcting those too as part of this PR?

**Comment by GCHQ-Developer-847** [comment]
Hi @BenHammersley, we will just need the above changes to be implemented before we can progress with merging this pull request - thanks 🙂

**Comment by BenHammersley** [comment]
Yes, getting onto it today - apologies for the delay

**Comment by GCHQ-Developer-847** [comment]
> Yes, getting onto it today - apologies for the delay

No worries at all, thank you!

**Pull request closed without merging**
