### PR TITLE
docs(root): replaced fig2 in date picker guidance

### PR DESCRIPTION
**Pull request by srt544**
Replaced fig2 in date picker

Tell us, in a few words, what the changes are.
Replaced fig2 in date picker guidance with correct image

Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.

#1041

### CODE REVIEW

**Comment by MI6-94** [comment]
Review the high definition quality of the image against the others, slightly blurry. This should bee exported from Figma as 'x2 PNG'.

**Review by ad9242 — CHANGES_REQUESTED** [review]
I think a rebase will mean the package-lock.json fixes will no longer be required. Would also be good to squash to a single commit

**Comment by GCHQ-Developer-094** [comment]
Do the dates in the final image also need changed, or is this the correct behaviour?

**Comment by srt544** [comment]
> Review the high definition quality of the image against the others, slightly blurry. This should be exported from Figma as 'x2 PNG'.

I have noticed and have now replaced it with a higher resolution image

**Review by srt544 — COMMENTED** [review]
I will take note of this and aim to do it in one commit

**Review by ad9242 — CHANGES_REQUESTED** [review]
I think you can remove all the files except the image from this commit. It shouldn't require package-lock.json changes & the other files look like line endings have changed, but not worth committing

**Comment by gd2910** [comment]
These images also need updating;
image
Date input should read - 29/07/2024
image
Date picker `year` should read 2023, as this date would be in the past and invalid

**Comment by GCHQ-Developer-465** [comment]
> These images also need updating;
> 
> image
> 
> Date input should read - 29/07/2024
> 
> image
> 
> Date picker `year` should read 2023, as this date would be in the past and invalid

Updated the images 😊

**Pull request merged**
