### PR TITLE
fix(root): added empty href's to guidance.mdx and code.mdx

### LINKED ISSUE #866: Add blank href attribute to ic-side-navigation 'app-icon' slot
## Summary of the bug

When viewing the IcSideNavigation examples on the Code or Guidance pages, if a user clicks the 'app-icon' they are sent back to the design system home screen.

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to the [Side Navigation](https://design.sis.gov.uk/components/side-navigation) guidance
2. Click on the 'app-icon' in the example
3. Get directed back to the home page

## 📸 Screenshots or code

Adding a redundant href to IcSideNavigation will stop the redirect.

`<IcSideNavigation
    appTitle="ACME coffee shop"
    version="v0.0.7"
    status="Alpha"
    disableAutoParentStyling
    inline
    href="#"
  >`

Other examples on the Code page will also need to be changed.

## 🧐 Expected behaviour

Now when a user clicks the 'app-icon' they will not be redirected.

### PR DESCRIPTION
**Pull request by AlexVCS**
fix #866

## Summary of the changes

added empty href's to guidance.mdx and code.mdx

## Related issue

#866 

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [✅ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

### CODE REVIEW

**Comment by GCHQ-Developer-465** [comment]
Hey @AlexVCS 👋 

Thank you for your contribution. 

If possible please can you squash your commits so that there is only 1 commit. This ensures a clean workflow for the project. 

You can do this by following these steps:

- Enter 'git reset --soft HEAD~2' in your terminal (this will remove your last 2 commits, however it will keep your changes)
- Then do a 'git commit' as normal (this will turn your changes into 1 commit)

Hope this helps. Please do ask if you need any more guidance. But once again thank you for contributing to the project 😊

**Comment by AlexVCS** [comment]
> Hey @AlexVCS 👋
> 
> Thank you for your contribution.
> 
> If possible please can you squash your commits so that there is only 1 commit. This ensures a clean workflow for the project.
> 
> You can do this by following these steps:
> 
> * Enter 'git reset --soft HEAD~2' in your terminal (this will remove your last 2 commits, however it will keep your changes)
> * Then do a 'git commit' as normal (this will turn your changes into 1 commit)
> 
> Hope this helps. Please do ask if you need any more guidance. But once again thank you for contributing to the project 😊

Ok I did this. I hope it's right now! Please let me know if I need to do anything else.

**Review by GCHQ-Developer-465 — DISMISSED** [review]
Great work! Thank you @AlexVCS 😃

**Comment by GCHQ-Developer-530** [comment]
> > Sorry @AlexVCS, just noticed the commit message isn't quite right. Please could you update it so that the start is fix(root) rather than fix(add empty href's). The work looks good, I'll be happy to approve after this 😊 thank you
> 
> I need to do a rebase to do this right? I tried doing it but haven't been able to yet. Any insights into how to do that would be appreciated!

Maybe a `git reset --soft HEAD^1` might work better, so you can re-commit your work with the new commit message? It looks like there's conflicts on this PR after the release as well, so I'd suggest doing `git fetch` and then `git rebase origin/develop` and hopefully there shouldn't be any merge conflicts locally.

**Comment by AlexVCS** [comment]
> > > Sorry @AlexVCS, just noticed the commit message isn't quite right. Please could you update it so that the start is fix(root) rather than fix(add empty href's). The work looks good, I'll be happy to approve after this 😊 thank you
> > 
> > 
> > I need to do a rebase to do this right? I tried doing it but haven't been able to yet. Any insights into how to do that would be appreciated!
> 
> Maybe a `git reset --soft HEAD^1` might work better, so you can re-commit your work with the new commit message? It looks like there's conflicts on this PR after the release as well, so I'd suggest doing `git fetch` and then `git rebase origin/develop` and hopefully there shouldn't be any merge conflicts locally.

I tried to do it but it looks like the conflicts remain. Any advice on how to fix it?

**Comment by GCHQ-Developer-530** [comment]
> > > > Sorry @AlexVCS, just noticed the commit message isn't quite right. Please could you update it so that the start is fix(root) rather than fix(add empty href's). The work looks good, I'll be happy to approve after this 😊 thank you
> > > 
> > > 
> > > I need to do a rebase to do this right? I tried doing it but haven't been able to yet. Any insights into how to do that would be appreciated!
> > 
> > 
> > Maybe a `git reset --soft HEAD^1` might work better, so you can re-commit your work with the new commit message? It looks like there's conflicts on this PR after the release as well, so I'd suggest doing `git fetch` and then `git rebase origin/develop` and hopefully there shouldn't be any merge conflicts locally.
> 
> I tried to do it but it looks like the conflicts remain. Any advice on how to fix it?

It might be because your forked develop branch is behind our develop branch. I've had a look around, and I think doing something like this might work.

1. `git remote add upstream https://github.com/mi6/ic-design-system.git`
2. `git fetch upstream`
3. `git rebase upstream/develop`

**Comment by GCHQ-Developer-112** [comment]
Looks good! Happy to approve once it's been rebased 😀 
Thank you for your contribution @AlexVCS 🌟

**Comment by AlexVCS** [comment]
> > > > > Sorry @AlexVCS, just noticed the commit message isn't quite right. Please could you update it so that the start is fix(root) rather than fix(add empty href's). The work looks good, I'll be happy to approve after this 😊 thank you
> > > > 
> > > > 
> > > > I need to do a rebase to do this right? I tried doing it but haven't been able to yet. Any insights into how to do that would be appreciated!
> > > 
> > > 
> > > Maybe a `git reset --soft HEAD^1` might work better, so you can re-commit your work with the new commit message? It looks like there's conflicts on this PR after the release as well, so I'd suggest doing `git fetch` and then `git rebase origin/develop` and hopefully there shouldn't be any merge conflicts locally.
> > 
> > 
> > I tried to do it but it looks like the conflicts remain. Any advice on how to fix it?
> 
> It might be because your forked develop branch is behind our develop branch. I've had a look around, and I think doing something like this might work.
> 
> 1. `git remote add upstream https://github.com/mi6/ic-design-system.git`
> 2. `git fetch upstream`
> 3. `git rebase upstream/develop`

I had that upstream already, and I've now rebased. Is this OK now?

**Review by GCHQ-Developer-112 — APPROVED** [review]

**Review by GCHQ-Developer-112 — CHANGES_REQUESTED** [review]
Hi @AlexVCS, sorry I've just looked over this PR again, it seems the commit message has gone wrong

**Comment by AlexVCS** [comment]
> Hey @AlexVCS,
> 
> You are very close to contributing! 🙌
> 
> Apologies you will need to a rebase and fix your commit message as it has been wrapped round the fix bracket "fix(fix(root)): added empty href's to guidance.mdx and code.mdx" as it should be "fix(root): added empty href's to guidance.mdx and code.md".
> 
> Try running through the steps mentioned above again 😊
> 
> Please let us know if you need a hand!
> 
> Thank you again for your contribution.

I think I might have fixed it now. Is it better?

**Comment by GCHQ-Developer-530** [comment]
> > Hey @AlexVCS,
> > You are very close to contributing! 🙌
> > Apologies you will need to a rebase and fix your commit message as it has been wrapped round the fix bracket "fix(fix(root)): added empty href's to guidance.mdx and code.mdx" as it should be "fix(root): added empty href's to guidance.mdx and code.md".
> > Try running through the steps mentioned above again 😊
> > Please let us know if you need a hand!
> > Thank you again for your contribution.
> 
> I think I might have fixed it now. Is it better?

Looks like it just needs another rebase, and to squash the merge commit into your fix(root) commit and then it should be good to go 😊 thank you for your patience with this

**Comment by AlexVCS** [comment]
> > > Hey @AlexVCS,
> > > You are very close to contributing! 🙌
> > > Apologies you will need to a rebase and fix your commit message as it has been wrapped round the fix bracket "fix(fix(root)): added empty href's to guidance.mdx and code.mdx" as it should be "fix(root): added empty href's to guidance.mdx and code.md".
> > > Try running through the steps mentioned above again 😊
> > > Please let us know if you need a hand!
> > > Thank you again for your contribution.
> > 
> > 
> > I think I might have fixed it now. Is it better?
> 
> Looks like it just needs another rebase, and to squash the merge commit into your fix(root) commit and then it should be good to go 😊 thank you for your patience with this

I rebased but am not sure how to squash as I tried running git reset --soft HEAD~2 even with 1, 3, and 4 instead of 2 and none of those did anything. It's not right now is it?

**Comment by GCHQ-Developer-530** [comment]
> > > > Hey @AlexVCS,
> > > > You are very close to contributing! 🙌
> > > > Apologies you will need to a rebase and fix your commit message as it has been wrapped round the fix bracket "fix(fix(root)): added empty href's to guidance.mdx and code.mdx" as it should be "fix(root): added empty href's to guidance.mdx and code.md".
> > > > Try running through the steps mentioned above again 😊
> > > > Please let us know if you need a hand!
> > > > Thank you again for your contribution.
> > > 
> > > 
> > > I think I might have fixed it now. Is it better?
> > 
> > 
> > Looks like it just needs another rebase, and to squash the merge commit into your fix(root) commit and then it should be good to go 😊 thank you for your patience with this
> 
> I rebased but am not sure how to squash as I tried running git reset --soft HEAD~2 even with 1, 3, and 4 instead of 2 and none of those did anything. It's not right now is it?

Perfect! That's worked for squashing the commits into one. Now I think the only issue is the "fix(fix(root))" in your commit message. If you could update that to be "fix(root)" not duplicated then I'm happy to approve

**Comment by AlexVCS** [comment]
> > > > > Hey @AlexVCS,
> > > > > You are very close to contributing! 🙌
> > > > > Apologies you will need to a rebase and fix your commit message as it has been wrapped round the fix bracket "fix(fix(root)): added empty href's to guidance.mdx and code.mdx" as it should be "fix(root): added empty href's to guidance.mdx and code.md".
> > > > > Try running through the steps mentioned above again 😊
> > > > > Please let us know if you need a hand!
> > > > > Thank you again for your contribution.
> > > > 
> > > > 
> > > > I think I might have fixed it now. Is it better?
> > > 
> > > 
> > > Looks like it just needs another rebase, and to squash the merge commit into your fix(root) commit and then it should be good to go 😊 thank you for your patience with this
> > 
> > 
> > I rebased but am not sure how to squash as I tried running git reset --soft HEAD~2 even with 1, 3, and 4 instead of 2 and none of those did anything. It's not right now is it?
> 
> Perfect! That's worked for squashing the commits into one. Now I think the only issue is the "fix(fix(root))" in your commit message. If you could update that to be "fix(root)" not duplicated then I'm happy to approve

Ok great, but I'm sorry, I'm not confident I know exactly what to do. I would like to not keep committing the wrong thing or way. What would you suggest?

**Comment by GCHQ-Developer-530** [comment]
> > > > > > Hey @AlexVCS,
> > > > > > You are very close to contributing! 🙌
> > > > > > Apologies you will need to a rebase and fix your commit message as it has been wrapped round the fix bracket "fix(fix(root)): added empty href's to guidance.mdx and code.mdx" as it should be "fix(root): added empty href's to guidance.mdx and code.md".
> > > > > > Try running through the steps mentioned above again 😊
> > > > > > Please let us know if you need a hand!
> > > > > > Thank you again for your contribution.
> > > > > 
> > > > > 
> > > > > I think I might have fixed it now. Is it better?
> > > > 
> > > > 
> > > > Looks like it just needs another rebase, and to squash the merge commit into your fix(root) commit and then it should be good to go 😊 thank you for your patience with this
> > > 
> > > 
> > > I rebased but am not sure how to squash as I tried running git reset --soft HEAD~2 even with 1, 3, and 4 instead of 2 and none of those did anything. It's not right now is it?
> > 
> > 
> > Perfect! That's worked for squashing the commits into one. Now I think the only issue is the "fix(fix(root))" in your commit message. If you could update that to be "fix(root)" not duplicated then I'm happy to approve
> 
> Ok great, but I'm sorry, I'm not confident I know exactly what to do. I would like to not keep committing the wrong thing or way. What would you suggest?

No worries. I'd suggest perhaps doing a `git reset --soft HEAD~1` and then when you run through the `git commit` steps again with commitizen you should just need to choose `fix` for the first step, then type `root` for the scope, and then add your regular commit message like with your other commits. Let us know if you run into any issues with the process and we'll find another way around it.

**Comment by GCHQ-Developer-530** [comment]
Hi @AlexVCS as this has gone 2 weeks without an update, we're going to close this PR. Feel free to reopen this if you feel there is more work you can do on it. Thanks again 😊

**Pull request closed without merging**
