### PR TITLE
Feature/125 google analytics env variable

### PR DESCRIPTION
**Pull request by MI6-451**
## Summary of the changes
Allows the code associated with cookies to be enable or disabled via the tracking id environment variable. When disabled the cookies banner will not appear, the cookies policy link is removed from the footer and the switch on the cookies policy page is disabled.

## Related issue
#125 

## Checklist
- [x] I have manually accessibility tested any changes, if relevant.

### CODE REVIEW

**Comment by GCHQ-Developer-112** [comment]
You may need to rebase off develop to make sure only your changes will be committed

**Comment by MI6-451** [comment]
> You may need to rebase off develop to make sure only your changes will be committed

I believe I have rebased from develop, I think the other changes are prettier fixes.

**Comment by GCHQ-Developer-112** [comment]
> > You may need to rebase off develop to make sure only your changes will be committed
> 
> I believe I have rebased from develop, I think the other changes are prettier fixes.

When you do a git rebase, does it show that you're up to date? When I pulled down your branch and tried a rebase, it showed changes. I haven't done a push up though 

Screenshot 2022-12-13 at 17 19 46

**Comment by MI6-451** [comment]
> > > You may need to rebase off develop to make sure only your changes will be committed
> > 
> > 
> > I believe I have rebased from develop, I think the other changes are prettier fixes.
> 
> When you do a git rebase, does it show that you're up to date? When I pulled down your branch and tried a rebase, it showed changes. I haven't done a push up though
> 
> Screenshot 2022-12-13 at 17 19 46

Was showing as up to date for me and have just grabbed the latest changes and it says the same again. I did notice that I'd opened the pull request to main though so have fixed that with develop as destination branch.

**Review by GCHQ-Developer-112 — APPROVED** [review]

**Review by GCHQ-Developer-465 — APPROVED** [review]

**Pull request merged**
