### PR TITLE
docs(root): update radio and checkbox conditional dynamic examples

### PR DESCRIPTION
**Pull request by GCHQ-Developer-530**
## Summary of the changes

Update radio and checkbox conditional dynamic examples so that they don't move when the additional field shows

## Related issue

#655 

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

### CODE REVIEW

**Review by GCHQ-Developer-465 — APPROVED** [review]

**Review by GCHQ-Developer-112 — CHANGES_REQUESTED** [review]
Screenshot 2024-01-19 at 10 55 17
At around 800px screen width, the input field overflows its parent container

**Review by GCHQ-Developer-465 — COMMENTED** [review]
Screenshot 2024-01-19 at 11 33 21

This still occurs at this breakpoint

**Review by GCHQ-Developer-465 — COMMENTED** [review]
Still getting similar issue but not as bad as before... Is this worth running past @DBD324 ? 
Screenshot 2024-01-19 at 13 47 50

**Comment by DBD324** [comment]
> Still getting similar issue but not as bad as before... Is this worth running past @DBD324 ? Screenshot 2024-01-19 at 13 47 50

I am also seeing this issue with Edge on Windows. Seems to be in the smallest sizes of the medium breakpoint. At 769 we don't have enough padding. I would either expect the text field to shrink to maintain 16px padding with edge of component demo, or we could reduce size of text field so that this doesn't visibly occur. Seems to work nicely on the radio button examples though.

**Review by GCHQ-Developer-465 — APPROVED** [review]
Awesome work! Looks good now. Worth having a re-review with @DBD324 to double check. Thanks

**Review by GCHQ-Developer-112 — APPROVED** [review]

**Review by DBD324 — APPROVED** [review]
Great, this works much more nicely now. Thanks

**Pull request merged**
