### PR TITLE
docs(root): added semantic typography

### PR DESCRIPTION
**Pull request by MI6-94**
added semantic typography

### CODE REVIEW

**Comment by GCHQ-Developer-299** [comment]
Curious side effect here (testing out your branch locally) where the headings have large margins when you have semantic elements inside them 
Screenshot 2024-05-17 at 15 34 14

**Comment by ad9242** [comment]
as @GCHQ-Developer-299, says there seems to be a problem. I think it is to do with the way the site substitutes `<H1>`etc for ic-typography elements. so there are nested elements when you inspect the code:

image

**Review by GCHQ-Developer-299 — CHANGES_REQUESTED** [review]
Please squash your commits, and then i'll be happy to approve!

**Review by GCHQ-Developer-112 — COMMENTED** [review]
Please change the "semantice" to "semantic" in your commit message

**Comment by GCHQ-Developer-112** [comment]
This work is covered in the Stackblitz ticket already and could cause conflicts. I believe this PR should be closed

**Comment by GCHQ-Developer-112** [comment]
Closing for the reason above

**Pull request closed without merging**
