### PR TITLE
fix(root): fixes SSR in Gatsby

### PR DESCRIPTION
**Pull request by ad9242**
## Summary of the changes
Stops whole page content reloading on navigation. Content is now visible when javascript disabled.
Styles no longer applied using className as these were not applied when JS disabled.
Also uses web components rather than React wrapper. React wrapper still required for use in mdx files.

## Related issue
#115 

## Checklist
- [x] I have manually accessibility tested any changes, if relevant.

### CODE REVIEW

**Review by MI6-451 — APPROVED** [review]

**Review by MI6-255 — COMMENTED** [review]
Great work on this, looks great without JS. Just a point, on initial page load, the Top Navigation does have a flicker where it is enlarged then quickly reduces. There be anything we can do about that? This is new behaviour since the changes.

**Comment by ad9242** [comment]
> Great work on this, looks great without JS. Just a point, on initial page load, the Top Navigation does have a flicker where it is enlarged then quickly reduces. There be anything we can do about that? This is new behaviour since the changes.

This will be resolved once latest ui-kit components are released

**Review by MI6-451 — APPROVED** [review]

**Comment by GCHQ-Developer-112** [comment]
Hey @ad9242, I think this branch needs to be rebased off develop. It's currently pulling other commits into this PR

**Review by GCHQ-Developer-112 — DISMISSED** [review]
Having spoken to @ad9242, I'm happy to approve this PR. We've agreed that there should be a message communicating that the site works best with JavaScript enabled. Another ticket will be created for this message.

Overall, looks really good 🤩 Great work @ad9242!

**Review by MI6-451 — APPROVED** [review]

**Comment by ad9242** [comment]
closed as replaced by https://github.com/mi6/ic-design-system/pull/166

**Pull request closed without merging**
